# -*- coding: utf-8 -*-
"""ML_Lab_2_220041120.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1opc1rp9uKAWbSacEYiQh7inGRaqJeUKr
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


from sklearn.preprocessing import LabelEncoder,OneHotEncoder
from sklearn.preprocessing import MinMaxScaler,StandardScaler

# %matplotlib inline

sns.set_theme(style="whitegrid")
print("All libraries lodeaded successfully")

import pandas as pd

url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
df = pd.read_csv(url)

print("This is the head")
print(df.head())

print("This is the Shape")
print(f"shape :{df.shape}")

print("TAIL")
print(df.tail())

print("info")
print(df.info())

print("SAMPLE TEST")
print(df.sample(5,random_state=43))

print("Columns")
print(df.columns.tolist())

print("TYPES")
print(df.dtypes)

print("DESCRIBE")
print(df.describe)


print('Object')
print(df.describe(include='object'))

print('Unique')
print(df.nunique())


print(df['Pclass'].value_counts())

print(df['Survived'].value_counts())



print("Missing value")
print(df.isnull().sum())


plt.figure(figsize=(10,4))
sns.heatmap(df.isnull(),cbar=False,cmap='viridis',yticklabels=False)
plt.title("Missing vaue Map (yellow= missing)")
plt.tight_layout()
plt.show()